export interface Creator {
  slug: string;
  name: string;
  years: string;
  bio: string;
  influencedBy: string[];
  influenced: string[];
  works: Work[];
}

export interface Work {
  slug: string;
  title: string;
  year: number;
  type: "book" | "screenplay" | "article" | "essay" | "poem";
  description: string;
}

export const creators: Creator[] = [
  // ==================== ROOTS OF MODERNISM ====================
  {
    slug: "twain",
    name: "Mark Twain",
    years: "1835-1910",
    bio: "Father of American literature whose vernacular storytelling and satirical voice shaped every generation after him.",
    influencedBy: [],
    influenced: ["hemingway", "faulkner", "vonnegut"],
    works: [
      {
        slug: "huck-finn",
        title: "Adventures of Huckleberry Finn",
        year: 1884,
        type: "book",
        description: "The great American novel",
      },
      {
        slug: "tom-sawyer",
        title: "The Adventures of Tom Sawyer",
        year: 1876,
        type: "book",
        description: "Boyhood along the Mississippi",
      },
    ],
  },
  {
    slug: "chekhov",
    name: "Anton Chekhov",
    years: "1860-1904",
    bio: "Russian playwright and short story master whose understated style revolutionized modern drama and fiction.",
    influencedBy: [],
    influenced: ["hemingway", "carver", "ishiguro"],
    works: [
      {
        slug: "cherry-orchard",
        title: "The Cherry Orchard",
        year: 1904,
        type: "book",
        description: "Tragicomedy of Russian gentry",
      },
      {
        slug: "lady-with-dog",
        title: "The Lady with the Dog",
        year: 1899,
        type: "book",
        description: "Masterpiece of the short story form",
      },
    ],
  },
  {
    slug: "wells",
    name: "H.G. Wells",
    years: "1866-1946",
    bio: "Father of science fiction who imagined time travel, alien invasion, and invisible men before anyone else.",
    influencedBy: [],
    influenced: [
      "huxley",
      "bradbury",
      "asimov",
      "clarke",
      "heinlein",
      "l-engle",
    ],
    works: [
      {
        slug: "time-machine",
        title: "The Time Machine",
        year: 1895,
        type: "book",
        description: "First great time travel story",
      },
      {
        slug: "war-of-worlds",
        title: "The War of the Worlds",
        year: 1898,
        type: "book",
        description: "Alien invasion of Earth",
      },
    ],
  },
  {
    slug: "stein",
    name: "Gertrude Stein",
    years: "1874-1946",
    bio: "Avant-garde writer and Paris salon host who mentored the Lost Generation and pioneered literary modernism.",
    influencedBy: [],
    influenced: ["hemingway", "fitzgerald"],
    works: [
      {
        slug: "three-lives",
        title: "Three Lives",
        year: 1909,
        type: "book",
        description: "Experimental portraits of women",
      },
      {
        slug: "tender-buttons",
        title: "Tender Buttons",
        year: 1914,
        type: "book",
        description: "Radical prose poetry",
      },
    ],
  },
  {
    slug: "joyce",
    name: "James Joyce",
    years: "1882-1941",
    bio: "Irish modernist whose stream of consciousness technique and linguistic invention redefined the novel.",
    influencedBy: [],
    influenced: ["faulkner", "woolf", "delillo", "baldwin"],
    works: [
      {
        slug: "ulysses",
        title: "Ulysses",
        year: 1922,
        type: "book",
        description: "One day in Dublin, all of literature",
      },
      {
        slug: "dubliners",
        title: "Dubliners",
        year: 1914,
        type: "book",
        description: "Epiphanies of Irish life",
      },
    ],
  },
  {
    slug: "woolf",
    name: "Virginia Woolf",
    years: "1882-1941",
    bio: "Modernist novelist and essayist who pioneered stream of consciousness and feminist literary criticism.",
    influencedBy: ["joyce"],
    influenced: ["morrison", "plath", "robinson"],
    works: [
      {
        slug: "mrs-dalloway",
        title: "Mrs Dalloway",
        year: 1925,
        type: "book",
        description: "One day in post-war London",
      },
      {
        slug: "to-lighthouse",
        title: "To the Lighthouse",
        year: 1927,
        type: "book",
        description: "Memory, loss, and art",
      },
    ],
  },
  {
    slug: "kafka",
    name: "Franz Kafka",
    years: "1883-1924",
    bio: "Czech-born writer whose nightmarish visions of bureaucracy and alienation gave the world 'Kafkaesque.'",
    influencedBy: [],
    influenced: ["borges", "murakami", "roth", "kaufman"],
    works: [
      {
        slug: "the-trial",
        title: "The Trial",
        year: 1925,
        type: "book",
        description: "Arrested for an unnamed crime",
      },
      {
        slug: "metamorphosis",
        title: "The Metamorphosis",
        year: 1915,
        type: "book",
        description: "Waking up as an insect",
      },
    ],
  },
  {
    slug: "fitzgerald",
    name: "F. Scott Fitzgerald",
    years: "1896-1940",
    bio: "Chronicler of the Jazz Age whose lyrical prose captured American dreams and disillusion.",
    influencedBy: ["stein"],
    influenced: [],
    works: [
      {
        slug: "great-gatsby",
        title: "The Great Gatsby",
        year: 1925,
        type: "book",
        description: "The American Dream, shattered",
      },
      {
        slug: "tender-is-night",
        title: "Tender Is the Night",
        year: 1934,
        type: "book",
        description: "Expatriate decline on the Riviera",
      },
    ],
  },
  {
    slug: "tolkien",
    name: "J.R.R. Tolkien",
    years: "1892-1973",
    bio: "Philologist who invented modern fantasy, building Middle-earth from languages up.",
    influencedBy: [],
    influenced: ["le-guin", "l-engle"],
    works: [
      {
        slug: "lord-of-rings",
        title: "The Lord of the Rings",
        year: 1954,
        type: "book",
        description: "The quest to destroy the One Ring",
      },
      {
        slug: "the-hobbit",
        title: "The Hobbit",
        year: 1937,
        type: "book",
        description: "There and back again",
      },
    ],
  },

  // ==================== AMERICAN MASTERS ====================
  {
    slug: "hemingway",
    name: "Ernest Hemingway",
    years: "1899-1961",
    bio: "American novelist and short story writer, known for his terse prose and the 'iceberg theory'.",
    influencedBy: ["chekhov", "stein", "twain"],
    influenced: ["carver", "mccarthy", "didion", "baldwin"],
    works: [
      {
        slug: "sun-also-rises",
        title: "The Sun Also Rises",
        year: 1926,
        type: "book",
        description: "Lost Generation classic",
      },
      {
        slug: "old-man-sea",
        title: "The Old Man and the Sea",
        year: 1952,
        type: "book",
        description: "Pulitzer Prize winner",
      },
    ],
  },
  {
    slug: "faulkner",
    name: "William Faulkner",
    years: "1897-1962",
    bio: "American writer and Nobel laureate, known for experimental narrative and Southern Gothic themes.",
    influencedBy: ["joyce", "twain"],
    influenced: [
      "mccarthy",
      "marquez",
      "morrison",
      "oconnor",
      "ward",
      "harper-lee",
      "roth",
      "erdrich",
      "johnson",
    ],
    works: [
      {
        slug: "sound-fury",
        title: "The Sound and the Fury",
        year: 1929,
        type: "book",
        description: "Stream of consciousness classic",
      },
      {
        slug: "absalom-absalom",
        title: "Absalom, Absalom!",
        year: 1936,
        type: "book",
        description: "Southern tragedy",
      },
    ],
  },
  {
    slug: "oconnor",
    name: "Flannery O'Connor",
    years: "1925-1964",
    bio: "Southern Gothic master whose darkly comic fiction explored grace, violence, and the grotesque.",
    influencedBy: ["faulkner"],
    influenced: [],
    works: [
      {
        slug: "wise-blood",
        title: "Wise Blood",
        year: 1952,
        type: "book",
        description: "A man founds a church without Christ",
      },
      {
        slug: "good-man-hard-find",
        title: "A Good Man Is Hard to Find",
        year: 1955,
        type: "book",
        description: "Unforgettable Southern Gothic stories",
      },
    ],
  },
  {
    slug: "plath",
    name: "Sylvia Plath",
    years: "1932-1963",
    bio: "Confessional poet and novelist whose searing intensity made her an icon of literary self-revelation.",
    influencedBy: ["woolf"],
    influenced: [],
    works: [
      {
        slug: "the-bell-jar",
        title: "The Bell Jar",
        year: 1963,
        type: "book",
        description: "Autobiographical descent into breakdown",
      },
      {
        slug: "ariel",
        title: "Ariel",
        year: 1965,
        type: "book",
        description: "Posthumous poems of fierce brilliance",
      },
    ],
  },
  {
    slug: "morrison",
    name: "Toni Morrison",
    years: "1931-2019",
    bio: "Nobel laureate who excavated the African American experience with lyrical, mythic power.",
    influencedBy: ["faulkner", "woolf"],
    influenced: ["whitehead", "ward", "adichie", "walker", "erdrich"],
    works: [
      {
        slug: "beloved",
        title: "Beloved",
        year: 1987,
        type: "book",
        description: "A ghost story about slavery's aftermath",
      },
      {
        slug: "song-of-solomon",
        title: "Song of Solomon",
        year: 1977,
        type: "book",
        description: "Flight, identity, and myth",
      },
    ],
  },
  {
    slug: "angelou",
    name: "Maya Angelou",
    years: "1928-2014",
    bio: "Memoirist, poet, and civil rights voice whose autobiographies transformed American letters.",
    influencedBy: [],
    influenced: ["walker"],
    works: [
      {
        slug: "caged-bird",
        title: "I Know Why the Caged Bird Sings",
        year: 1969,
        type: "book",
        description: "Coming of age in the segregated South",
      },
      {
        slug: "still-i-rise",
        title: "And Still I Rise",
        year: 1978,
        type: "book",
        description: "Defiant, joyful poetry",
      },
    ],
  },
  {
    slug: "didion",
    name: "Joan Didion",
    years: "1934-2021",
    bio: "Essayist and novelist whose cool, precise prose dissected California, politics, and grief.",
    influencedBy: ["hemingway"],
    influenced: ["simon"],
    works: [
      {
        slug: "slouching-bethlehem",
        title: "Slouching Towards Bethlehem",
        year: 1968,
        type: "article",
        description: "Essays on the 1960s counterculture",
      },
      {
        slug: "year-magical-thinking",
        title: "The Year of Magical Thinking",
        year: 2005,
        type: "book",
        description: "Memoir of sudden loss",
      },
    ],
  },
  {
    slug: "kerouac",
    name: "Jack Kerouac",
    years: "1922-1969",
    bio: "Beat Generation icon whose spontaneous prose captured the restless spirit of postwar America.",
    influencedBy: [],
    influenced: [],
    works: [
      {
        slug: "on-the-road",
        title: "On the Road",
        year: 1957,
        type: "book",
        description: "Jazz-fueled cross-country odyssey",
      },
      {
        slug: "dharma-bums",
        title: "The Dharma Bums",
        year: 1958,
        type: "book",
        description: "Beat Buddhism in the mountains",
      },
    ],
  },
  {
    slug: "vonnegut",
    name: "Kurt Vonnegut",
    years: "1922-2007",
    bio: "Satirist who blended science fiction with dark humor to expose the absurdity of war and modern life.",
    influencedBy: ["twain"],
    influenced: [],
    works: [
      {
        slug: "slaughterhouse-five",
        title: "Slaughterhouse-Five",
        year: 1969,
        type: "book",
        description: "Unstuck in time after Dresden",
      },
      {
        slug: "cats-cradle",
        title: "Cat's Cradle",
        year: 1963,
        type: "book",
        description: "Ice-nine and the end of the world",
      },
    ],
  },

  // ==================== MINIMALISM ====================
  {
    slug: "carver",
    name: "Raymond Carver",
    years: "1938-1988",
    bio: "American short story writer and poet, master of minimalism and the 'dirty realist' school.",
    influencedBy: ["hemingway", "chekhov"],
    influenced: ["wolff", "hempel", "murakami", "ford", "johnson"],
    works: [
      {
        slug: "what-we-talk-about",
        title: "What We Talk About When We Talk About Love",
        year: 1981,
        type: "book",
        description: "Minimalist masterpiece",
      },
      {
        slug: "cathedral",
        title: "Cathedral",
        year: 1983,
        type: "book",
        description: "Later, more expansive work",
      },
    ],
  },
  {
    slug: "wolff",
    name: "Tobias Wolff",
    years: "b. 1945",
    bio: "Memoirist and short story writer who brought warmth and moral complexity to literary minimalism.",
    influencedBy: ["carver"],
    influenced: [],
    works: [
      {
        slug: "this-boys-life",
        title: "This Boy's Life",
        year: 1989,
        type: "book",
        description: "Memoir of a difficult boyhood",
      },
      {
        slug: "in-garden-north",
        title: "In the Garden of the North American Martyrs",
        year: 1981,
        type: "book",
        description: "Precise, devastating stories",
      },
    ],
  },
  {
    slug: "hempel",
    name: "Amy Hempel",
    years: "b. 1951",
    bio: "Minimalist story writer whose compressed, elliptical prose makes every sentence carry enormous weight.",
    influencedBy: ["carver"],
    influenced: [],
    works: [
      {
        slug: "reasons-to-live",
        title: "Reasons to Live",
        year: 1985,
        type: "book",
        description: "Tiny, perfect stories",
      },
      {
        slug: "collected-stories",
        title: "The Collected Stories",
        year: 2006,
        type: "book",
        description: "A lifetime of brevity",
      },
    ],
  },
  {
    slug: "ford",
    name: "Richard Ford",
    years: "b. 1944",
    bio: "Novelist of American restlessness whose Frank Bascombe trilogy maps suburban consciousness.",
    influencedBy: ["carver"],
    influenced: [],
    works: [
      {
        slug: "the-sportswriter",
        title: "The Sportswriter",
        year: 1986,
        type: "book",
        description: "Quiet crisis in the suburbs",
      },
      {
        slug: "independence-day",
        title: "Independence Day",
        year: 1995,
        type: "book",
        description: "Pulitzer-winning sequel",
      },
    ],
  },

  // ==================== SOUTHERN / AMERICAN EPIC ====================
  {
    slug: "mccarthy",
    name: "Cormac McCarthy",
    years: "1933-2023",
    bio: "American novelist known for his sparse prose and violent, biblical themes.",
    influencedBy: ["hemingway", "faulkner"],
    influenced: ["coen-brothers", "gilligan"],
    works: [
      {
        slug: "blood-meridian",
        title: "Blood Meridian",
        year: 1985,
        type: "book",
        description: "Violent Western epic",
      },
      {
        slug: "the-road",
        title: "The Road",
        year: 2006,
        type: "book",
        description: "Post-apocalyptic father-son journey",
      },
    ],
  },
  {
    slug: "whitehead",
    name: "Colson Whitehead",
    years: "b. 1969",
    bio: "Two-time Pulitzer winner who reimagines American history through inventive, genre-bending fiction.",
    influencedBy: ["morrison"],
    influenced: [],
    works: [
      {
        slug: "underground-railroad",
        title: "The Underground Railroad",
        year: 2016,
        type: "book",
        description: "Literal railroad beneath the South",
      },
      {
        slug: "nickel-boys",
        title: "The Nickel Boys",
        year: 2019,
        type: "book",
        description: "Reform school horrors in Jim Crow Florida",
      },
    ],
  },
  {
    slug: "ward",
    name: "Jesmyn Ward",
    years: "b. 1977",
    bio: "Two-time National Book Award winner channeling the rural South with Faulknerian lyricism.",
    influencedBy: ["morrison", "faulkner"],
    influenced: [],
    works: [
      {
        slug: "sing-unburied",
        title: "Sing, Unburied, Sing",
        year: 2017,
        type: "book",
        description: "Ghosts and family in Mississippi",
      },
      {
        slug: "salvage-bones",
        title: "Salvage the Bones",
        year: 2011,
        type: "book",
        description: "Hurricane Katrina from inside",
      },
    ],
  },
  {
    slug: "vuong",
    name: "Ocean Vuong",
    years: "b. 1988",
    bio: "Vietnamese-American poet and novelist whose lyrical prose explores war, immigration, and identity.",
    influencedBy: [],
    influenced: [],
    works: [
      {
        slug: "on-earth-briefly",
        title: "On Earth We're Briefly Gorgeous",
        year: 2019,
        type: "book",
        description: "Letter from a son to his mother",
      },
      {
        slug: "night-sky-exit-wounds",
        title: "Night Sky with Exit Wounds",
        year: 2016,
        type: "book",
        description: "War and desire in verse",
      },
    ],
  },

  // ==================== POSTMODERNISM ====================
  {
    slug: "pynchon",
    name: "Thomas Pynchon",
    years: "b. 1937",
    bio: "Reclusive postmodernist whose encyclopedic novels weave conspiracy, entropy, and paranoia.",
    influencedBy: [],
    influenced: ["wallace", "delillo", "chabon", "egan"],
    works: [
      {
        slug: "gravitys-rainbow",
        title: "Gravity's Rainbow",
        year: 1973,
        type: "book",
        description: "WWII rockets and paranoia",
      },
      {
        slug: "crying-of-lot-49",
        title: "The Crying of Lot 49",
        year: 1966,
        type: "book",
        description: "Conspiracies in California",
      },
    ],
  },
  {
    slug: "delillo",
    name: "Don DeLillo",
    years: "b. 1936",
    bio: "Novelist of American paranoia whose prose captures the white noise of consumer culture and technology.",
    influencedBy: ["pynchon", "joyce"],
    influenced: ["egan"],
    works: [
      {
        slug: "white-noise",
        title: "White Noise",
        year: 1985,
        type: "book",
        description: "Fear of death in a toxic cloud",
      },
      {
        slug: "underworld",
        title: "Underworld",
        year: 1997,
        type: "book",
        description: "Cold War America in a baseball",
      },
    ],
  },
  {
    slug: "wallace",
    name: "David Foster Wallace",
    years: "1962-2008",
    bio: "Maximalist writer who turned self-consciousness into art, battling irony with sincerity.",
    influencedBy: ["pynchon", "delillo"],
    influenced: [],
    works: [
      {
        slug: "infinite-jest",
        title: "Infinite Jest",
        year: 1996,
        type: "book",
        description: "Entertainment, addiction, and tennis",
      },
      {
        slug: "supposedly-fun-thing",
        title: "A Supposedly Fun Thing I'll Never Do Again",
        year: 1997,
        type: "article",
        description: "Essays of hyper-aware observation",
      },
    ],
  },

  // ==================== SPECULATIVE FICTION ====================
  {
    slug: "huxley",
    name: "Aldous Huxley",
    years: "1894-1963",
    bio: "British novelist whose dystopia of pleasure and control remains terrifyingly prescient.",
    influencedBy: ["wells"],
    influenced: ["orwell", "lowry"],
    works: [
      {
        slug: "brave-new-world",
        title: "Brave New World",
        year: 1932,
        type: "book",
        description: "Dystopia through pleasure, not pain",
      },
      {
        slug: "doors-of-perception",
        title: "The Doors of Perception",
        year: 1954,
        type: "book",
        description: "Mescaline and consciousness",
      },
    ],
  },
  {
    slug: "orwell",
    name: "George Orwell",
    years: "1903-1950",
    bio: "British essayist and novelist whose political clarity gave the world Big Brother and Newspeak.",
    influencedBy: ["huxley"],
    influenced: ["atwood"],
    works: [
      {
        slug: "nineteen-eighty-four",
        title: "Nineteen Eighty-Four",
        year: 1949,
        type: "book",
        description: "Totalitarianism and thought control",
      },
      {
        slug: "animal-farm",
        title: "Animal Farm",
        year: 1945,
        type: "book",
        description: "Revolution betrayed, in a barnyard",
      },
    ],
  },
  {
    slug: "bradbury",
    name: "Ray Bradbury",
    years: "1920-2012",
    bio: "Poet of science fiction whose lyrical imagination turned rockets and book-burning into literature.",
    influencedBy: ["wells"],
    influenced: [],
    works: [
      {
        slug: "fahrenheit-451",
        title: "Fahrenheit 451",
        year: 1953,
        type: "book",
        description: "Firemen who burn books",
      },
      {
        slug: "martian-chronicles",
        title: "The Martian Chronicles",
        year: 1950,
        type: "book",
        description: "Colonizing Mars, losing Earth",
      },
    ],
  },
  {
    slug: "asimov",
    name: "Isaac Asimov",
    years: "1920-1992",
    bio: "Biochemist-turned-author who built the Foundation of science fiction with logic, robots, and galaxies.",
    influencedBy: ["wells"],
    influenced: ["dick"],
    works: [
      {
        slug: "foundation",
        title: "Foundation",
        year: 1951,
        type: "book",
        description: "Psychohistory and galactic empire",
      },
      {
        slug: "i-robot",
        title: "I, Robot",
        year: 1950,
        type: "book",
        description: "Three laws of robotics",
      },
    ],
  },
  {
    slug: "dick",
    name: "Philip K. Dick",
    years: "1928-1982",
    bio: "Visionary whose paranoid, reality-bending stories became the blueprint for cyberpunk and modern sci-fi film.",
    influencedBy: ["asimov"],
    influenced: [],
    works: [
      {
        slug: "do-androids-dream",
        title: "Do Androids Dream of Electric Sheep?",
        year: 1968,
        type: "book",
        description: "What makes us human (became Blade Runner)",
      },
      {
        slug: "man-high-castle",
        title: "The Man in the High Castle",
        year: 1962,
        type: "book",
        description: "Axis powers won WWII",
      },
    ],
  },
  {
    slug: "le-guin",
    name: "Ursula K. Le Guin",
    years: "1929-2018",
    bio: "American author of speculative fiction, influenced by anthropology and Taoism.",
    influencedBy: ["borges", "tolkien"],
    influenced: ["chiang", "butler", "jemisin"],
    works: [
      {
        slug: "left-hand",
        title: "The Left Hand of Darkness",
        year: 1969,
        type: "book",
        description: "Gender-fluid sci-fi classic",
      },
      {
        slug: "dispossessed",
        title: "The Dispossessed",
        year: 1974,
        type: "book",
        description: "Anarchist utopia/dystopia",
      },
    ],
  },
  {
    slug: "butler",
    name: "Octavia Butler",
    years: "1947-2006",
    bio: "Pioneering Black woman in sci-fi who explored power, identity, and survival through speculative fiction.",
    influencedBy: ["le-guin"],
    influenced: ["jemisin", "peele"],
    works: [
      {
        slug: "kindred",
        title: "Kindred",
        year: 1979,
        type: "book",
        description: "Time travel to antebellum slavery",
      },
      {
        slug: "parable-sower",
        title: "Parable of the Sower",
        year: 1993,
        type: "book",
        description: "Survival in a collapsing America",
      },
    ],
  },
  {
    slug: "atwood",
    name: "Margaret Atwood",
    years: "b. 1939",
    bio: "Canadian author whose speculative fiction dissects patriarchy, power, and ecological collapse.",
    influencedBy: ["orwell"],
    influenced: [],
    works: [
      {
        slug: "handmaids-tale",
        title: "The Handmaid's Tale",
        year: 1985,
        type: "book",
        description: "Theocratic dystopia and female subjugation",
      },
      {
        slug: "oryx-and-crake",
        title: "Oryx and Crake",
        year: 2003,
        type: "book",
        description: "Biotech apocalypse",
      },
    ],
  },
  {
    slug: "chiang",
    name: "Ted Chiang",
    years: "b. 1967",
    bio: "American speculative fiction writer, known for rigorous exploration of scientific and philosophical concepts.",
    influencedBy: ["le-guin", "borges"],
    influenced: [],
    works: [
      {
        slug: "stories-of-your-life",
        title: "Stories of Your Life and Others",
        year: 2002,
        type: "book",
        description: "Mind-bending short stories",
      },
      {
        slug: "exhalation",
        title: "Exhalation",
        year: 2019,
        type: "book",
        description: "More philosophical SF",
      },
    ],
  },
  {
    slug: "jemisin",
    name: "N.K. Jemisin",
    years: "b. 1972",
    bio: "First author to win three consecutive Hugo Awards, redefining epic fantasy with radical world-building.",
    influencedBy: ["le-guin", "butler"],
    influenced: [],
    works: [
      {
        slug: "fifth-season",
        title: "The Fifth Season",
        year: 2015,
        type: "book",
        description: "Second-person apocalyptic fantasy",
      },
      {
        slug: "hundred-thousand-kingdoms",
        title: "The Hundred Thousand Kingdoms",
        year: 2010,
        type: "book",
        description: "Gods in chains",
      },
    ],
  },

  // ==================== MAGIC REALISM / INTERNATIONAL ====================
  {
    slug: "borges",
    name: "Jorge Luis Borges",
    years: "1899-1986",
    bio: "Argentine fabulist whose labyrinths, mirrors, and infinite libraries made fiction a branch of philosophy.",
    influencedBy: ["kafka"],
    influenced: [
      "le-guin",
      "marquez",
      "chiang",
      "rushdie",
      "chabon",
      "kaufman",
    ],
    works: [
      {
        slug: "ficciones",
        title: "Ficciones",
        year: 1944,
        type: "book",
        description: "Stories as metaphysical puzzles",
      },
      {
        slug: "aleph",
        title: "The Aleph",
        year: 1949,
        type: "book",
        description: "A point containing all points",
      },
    ],
  },
  {
    slug: "marquez",
    name: "Gabriel Garcia Marquez",
    years: "1927-2014",
    bio: "Colombian Nobel laureate who made magic realism a global literary language.",
    influencedBy: ["faulkner", "borges"],
    influenced: ["rushdie"],
    works: [
      {
        slug: "hundred-years",
        title: "One Hundred Years of Solitude",
        year: 1967,
        type: "book",
        description: "Seven generations of the Buendia family",
      },
      {
        slug: "love-time-cholera",
        title: "Love in the Time of Cholera",
        year: 1985,
        type: "book",
        description: "Love that waits fifty years",
      },
    ],
  },
  {
    slug: "murakami",
    name: "Haruki Murakami",
    years: "b. 1949",
    bio: "Japanese novelist who blends Western minimalism with surreal, dreamlike narratives of loneliness.",
    influencedBy: ["carver", "kafka"],
    influenced: [],
    works: [
      {
        slug: "norwegian-wood",
        title: "Norwegian Wood",
        year: 1987,
        type: "book",
        description: "Memory and loss in 1960s Tokyo",
      },
      {
        slug: "wind-up-bird",
        title: "The Wind-Up Bird Chronicle",
        year: 1994,
        type: "book",
        description: "Surreal quest beneath Tokyo",
      },
    ],
  },
  {
    slug: "achebe",
    name: "Chinua Achebe",
    years: "1930-2013",
    bio: "Nigerian novelist who answered colonialism with the African novel's founding masterpiece.",
    influencedBy: [],
    influenced: ["adichie"],
    works: [
      {
        slug: "things-fall-apart",
        title: "Things Fall Apart",
        year: 1958,
        type: "book",
        description: "Igbo life before and after colonialism",
      },
      {
        slug: "no-longer-at-ease",
        title: "No Longer at Ease",
        year: 1960,
        type: "book",
        description: "Corruption and idealism in Nigeria",
      },
    ],
  },
  {
    slug: "adichie",
    name: "Chimamanda Ngozi Adichie",
    years: "b. 1977",
    bio: "Nigerian author whose fiction and essays on race, gender, and identity reshaped global conversations.",
    influencedBy: ["achebe", "morrison"],
    influenced: [],
    works: [
      {
        slug: "americanah",
        title: "Americanah",
        year: 2013,
        type: "book",
        description: "Immigration, race, and return",
      },
      {
        slug: "half-yellow-sun",
        title: "Half of a Yellow Sun",
        year: 2006,
        type: "book",
        description: "Love and war in Biafra",
      },
    ],
  },
  {
    slug: "rushdie",
    name: "Salman Rushdie",
    years: "b. 1947",
    bio: "British-Indian novelist whose magical realism and linguistic fireworks remixed the postcolonial novel.",
    influencedBy: ["borges", "marquez"],
    influenced: [],
    works: [
      {
        slug: "midnights-children",
        title: "Midnight's Children",
        year: 1981,
        type: "book",
        description: "India's independence through magic",
      },
      {
        slug: "satanic-verses",
        title: "The Satanic Verses",
        year: 1988,
        type: "book",
        description: "Migration, faith, and transformation",
      },
    ],
  },
  {
    slug: "ishiguro",
    name: "Kazuo Ishiguro",
    years: "b. 1954",
    bio: "British-Japanese Nobel laureate whose restrained, melancholic fiction explores memory, duty, and self-deception.",
    influencedBy: ["chekhov"],
    influenced: [],
    works: [
      {
        slug: "remains-of-day",
        title: "The Remains of the Day",
        year: 1989,
        type: "book",
        description: "A butler's unreliable memories",
      },
      {
        slug: "never-let-me-go",
        title: "Never Let Me Go",
        year: 2005,
        type: "book",
        description: "Quiet dystopia about clones",
      },
    ],
  },

  // ==================== SCREENWRITING ====================
  {
    slug: "wilder",
    name: "Billy Wilder",
    years: "1906-2002",
    bio: "Austrian-born director and screenwriter whose wit and cynicism defined Hollywood's golden age.",
    influencedBy: [],
    influenced: ["ephron", "tarantino"],
    works: [
      {
        slug: "some-like-it-hot",
        title: "Some Like It Hot",
        year: 1959,
        type: "screenplay",
        description: "The greatest comedy ever made",
      },
      {
        slug: "sunset-boulevard",
        title: "Sunset Boulevard",
        year: 1950,
        type: "screenplay",
        description: "Hollywood eats its own",
      },
    ],
  },
  {
    slug: "chayefsky",
    name: "Paddy Chayefsky",
    years: "1923-1981",
    bio: "American playwright and screenwriter, master of television drama and satirical film.",
    influencedBy: [],
    influenced: ["sorkin", "coen-brothers", "chase"],
    works: [
      {
        slug: "network",
        title: "Network",
        year: 1976,
        type: "screenplay",
        description: "Media satire, 'mad as hell'",
      },
      {
        slug: "marty",
        title: "Marty",
        year: 1955,
        type: "screenplay",
        description: "TV drama turned Oscar winner",
      },
    ],
  },
  {
    slug: "ephron",
    name: "Nora Ephron",
    years: "1941-2012",
    bio: "Screenwriter, director, and essayist who reinvented the romantic comedy with sharp, literate dialogue.",
    influencedBy: ["wilder"],
    influenced: ["waller-bridge", "cody"],
    works: [
      {
        slug: "when-harry-met-sally",
        title: "When Harry Met Sally...",
        year: 1989,
        type: "screenplay",
        description: "Can men and women be friends?",
      },
      {
        slug: "sleepless-in-seattle",
        title: "Sleepless in Seattle",
        year: 1993,
        type: "screenplay",
        description: "Fate and long-distance love",
      },
    ],
  },
  {
    slug: "sorkin",
    name: "Aaron Sorkin",
    years: "b. 1961",
    bio: "American screenwriter known for rapid-fire dialogue and idealistic characters.",
    influencedBy: ["chayefsky"],
    influenced: ["waller-bridge"],
    works: [
      {
        slug: "west-wing",
        title: "The West Wing",
        year: 1999,
        type: "screenplay",
        description: "Political drama series",
      },
      {
        slug: "social-network",
        title: "The Social Network",
        year: 2010,
        type: "screenplay",
        description: "Facebook origin story",
      },
    ],
  },
  {
    slug: "waller-bridge",
    name: "Phoebe Waller-Bridge",
    years: "b. 1985",
    bio: "British writer-actor who broke the fourth wall and the rom-com mold with unflinching honesty.",
    influencedBy: ["ephron", "sorkin"],
    influenced: ["coel"],
    works: [
      {
        slug: "fleabag",
        title: "Fleabag",
        year: 2016,
        type: "screenplay",
        description: "Grief, sex, and a hot priest",
      },
      {
        slug: "killing-eve",
        title: "Killing Eve",
        year: 2018,
        type: "screenplay",
        description: "Cat-and-mouse obsession",
      },
    ],
  },

  // ==================== PULITZER WINNERS ====================
  {
    slug: "harper-lee",
    name: "Harper Lee",
    years: "1926-2016",
    bio: "Alabama novelist whose debut became the most widely read American novel about racial injustice.",
    influencedBy: ["faulkner"],
    influenced: [],
    works: [
      {
        slug: "to-kill-mockingbird",
        title: "To Kill a Mockingbird",
        year: 1960,
        type: "book",
        description: "Justice and childhood innocence in the Deep South",
      },
      {
        slug: "go-set-watchman",
        title: "Go Set a Watchman",
        year: 2015,
        type: "book",
        description: "Scout revisits Maycomb as an adult",
      },
    ],
  },
  {
    slug: "walker",
    name: "Alice Walker",
    years: "b. 1944",
    bio: "Pulitzer-winning novelist and poet who centered Black women's stories with fierce grace and spirituality.",
    influencedBy: ["angelou", "morrison"],
    influenced: [],
    works: [
      {
        slug: "color-purple",
        title: "The Color Purple",
        year: 1982,
        type: "book",
        description: "Letters from a life of struggle and liberation",
      },
      {
        slug: "third-life-grange",
        title: "The Third Life of Grange Copeland",
        year: 1970,
        type: "book",
        description: "Three generations of a sharecropping family",
      },
    ],
  },
  {
    slug: "roth",
    name: "Philip Roth",
    years: "1933-2018",
    bio: "Prolific American novelist who turned Jewish-American identity into high literary art with savage wit.",
    influencedBy: ["kafka", "faulkner"],
    influenced: [],
    works: [
      {
        slug: "american-pastoral",
        title: "American Pastoral",
        year: 1997,
        type: "book",
        description: "The American dream collapses in the 1960s",
      },
      {
        slug: "portnoys-complaint",
        title: "Portnoy's Complaint",
        year: 1969,
        type: "book",
        description: "Confessional comedy of desire and guilt",
      },
    ],
  },
  {
    slug: "robinson",
    name: "Marilynne Robinson",
    years: "b. 1943",
    bio: "American novelist whose luminous, philosophical prose explores faith, memory, and the beauty of ordinary life.",
    influencedBy: ["woolf"],
    influenced: [],
    works: [
      {
        slug: "gilead",
        title: "Gilead",
        year: 2004,
        type: "book",
        description: "A dying preacher's letter to his son",
      },
      {
        slug: "housekeeping",
        title: "Housekeeping",
        year: 1980,
        type: "book",
        description: "Two sisters, a transient aunt, a lake",
      },
    ],
  },
  {
    slug: "chabon",
    name: "Michael Chabon",
    years: "b. 1963",
    bio: "Genre-blending Pulitzer winner who brings comic books, detective fiction, and Jewish history into literary fiction.",
    influencedBy: ["borges", "pynchon"],
    influenced: [],
    works: [
      {
        slug: "kavalier-clay",
        title: "The Amazing Adventures of Kavalier & Clay",
        year: 2000,
        type: "book",
        description: "Golden-age comics and wartime escape",
      },
      {
        slug: "wonder-boys",
        title: "Wonder Boys",
        year: 1995,
        type: "book",
        description: "A novelist's spectacular midlife crisis",
      },
    ],
  },
  {
    slug: "egan",
    name: "Jennifer Egan",
    years: "b. 1962",
    bio: "Innovative Pulitzer winner who experiments with time, structure, and technology in her fiction.",
    influencedBy: ["pynchon", "delillo"],
    influenced: [],
    works: [
      {
        slug: "goon-squad",
        title: "A Visit from the Goon Squad",
        year: 2010,
        type: "book",
        description: "Time and music, told in linked stories",
      },
      {
        slug: "candy-house",
        title: "The Candy House",
        year: 2022,
        type: "book",
        description: "Memory, identity, and collective consciousness",
      },
    ],
  },

  // ==================== NATIONAL BOOK AWARD / MAJOR LITERARY ====================
  {
    slug: "baldwin",
    name: "James Baldwin",
    years: "1924-1987",
    bio: "American novelist and essayist whose searing prose on race, sexuality, and identity made him a moral voice of the century.",
    influencedBy: ["joyce", "hemingway"],
    influenced: ["simon", "coel"],
    works: [
      {
        slug: "go-tell-mountain",
        title: "Go Tell It on the Mountain",
        year: 1953,
        type: "book",
        description: "Coming of age in Harlem's church",
      },
      {
        slug: "fire-next-time",
        title: "The Fire Next Time",
        year: 1963,
        type: "book",
        description: "Two essays on race in America",
      },
    ],
  },
  {
    slug: "erdrich",
    name: "Louise Erdrich",
    years: "b. 1954",
    bio: "Ojibwe-enrolled novelist who weaves Native American experience into multigenerational sagas of stunning complexity.",
    influencedBy: ["faulkner", "morrison"],
    influenced: [],
    works: [
      {
        slug: "round-house",
        title: "The Round House",
        year: 2012,
        type: "book",
        description: "A boy seeks justice on a reservation",
      },
      {
        slug: "love-medicine",
        title: "Love Medicine",
        year: 1984,
        type: "book",
        description: "Linked stories of two Ojibwe families",
      },
    ],
  },
  {
    slug: "johnson",
    name: "Denis Johnson",
    years: "1949-2017",
    bio: "American novelist and short story writer whose hallucinatory, desperate prose captured life at the margins.",
    influencedBy: ["carver", "faulkner"],
    influenced: [],
    works: [
      {
        slug: "jesus-son",
        title: "Jesus' Son",
        year: 1992,
        type: "book",
        description: "Linked stories of addiction and grace",
      },
      {
        slug: "tree-of-smoke",
        title: "Tree of Smoke",
        year: 2007,
        type: "book",
        description: "Vietnam War epic of faith and deception",
      },
    ],
  },

  // ==================== HUGO / SPECULATIVE ====================
  {
    slug: "clarke",
    name: "Arthur C. Clarke",
    years: "1917-2008",
    bio: "British science fiction visionary whose optimistic, technically rigorous imagination sent humanity to the stars.",
    influencedBy: ["wells"],
    influenced: [],
    works: [
      {
        slug: "2001-space-odyssey",
        title: "2001: A Space Odyssey",
        year: 1968,
        type: "book",
        description: "Humanity encounters alien intelligence",
      },
      {
        slug: "childhoods-end",
        title: "Childhood's End",
        year: 1953,
        type: "book",
        description: "Alien overlords guide human evolution",
      },
    ],
  },
  {
    slug: "heinlein",
    name: "Robert A. Heinlein",
    years: "1907-1988",
    bio: "Dean of science fiction whose libertarian, provocative novels defined the genre's golden age.",
    influencedBy: ["wells"],
    influenced: [],
    works: [
      {
        slug: "stranger-strange-land",
        title: "Stranger in a Strange Land",
        year: 1961,
        type: "book",
        description: "A human raised on Mars returns to Earth",
      },
      {
        slug: "starship-troopers",
        title: "Starship Troopers",
        year: 1959,
        type: "book",
        description: "Military service and citizenship in space",
      },
    ],
  },

  // ==================== NEWBERY / YA ====================
  {
    slug: "l-engle",
    name: "Madeleine L'Engle",
    years: "1918-2007",
    bio: "Newbery-winning author who blended science, faith, and fantasy into beloved young adult classics.",
    influencedBy: ["tolkien", "wells"],
    influenced: ["lowry"],
    works: [
      {
        slug: "wrinkle-in-time",
        title: "A Wrinkle in Time",
        year: 1962,
        type: "book",
        description: "Tesseract travel to rescue a father",
      },
      {
        slug: "wind-in-door",
        title: "A Wind in the Door",
        year: 1973,
        type: "book",
        description: "Journeying inside a mitochondrion",
      },
    ],
  },
  {
    slug: "lowry",
    name: "Lois Lowry",
    years: "b. 1937",
    bio: "Two-time Newbery medalist whose deceptively simple prose explores memory, freedom, and the cost of utopia.",
    influencedBy: ["l-engle", "huxley"],
    influenced: [],
    works: [
      {
        slug: "the-giver",
        title: "The Giver",
        year: 1993,
        type: "book",
        description: "A boy discovers his community's terrible secret",
      },
      {
        slug: "number-the-stars",
        title: "Number the Stars",
        year: 1989,
        type: "book",
        description: "Danish resistance through a child's eyes",
      },
    ],
  },

  // ==================== SCREENPLAY OSCAR WINNERS ====================
  {
    slug: "kaufman",
    name: "Charlie Kaufman",
    years: "b. 1958",
    bio: "American screenwriter-director whose meta, neurotic scripts blur the line between reality and imagination.",
    influencedBy: ["kafka", "borges"],
    influenced: [],
    works: [
      {
        slug: "eternal-sunshine",
        title: "Eternal Sunshine of the Spotless Mind",
        year: 2004,
        type: "screenplay",
        description: "Erasing memories of a failed romance",
      },
      {
        slug: "being-john-malkovich",
        title: "Being John Malkovich",
        year: 1999,
        type: "screenplay",
        description: "A portal into an actor's brain",
      },
    ],
  },
  {
    slug: "tarantino",
    name: "Quentin Tarantino",
    years: "b. 1963",
    bio: "American filmmaker whose encyclopedic cinephilia, non-linear storytelling, and crackling dialogue redefined cinema.",
    influencedBy: ["wilder"],
    influenced: [],
    works: [
      {
        slug: "pulp-fiction",
        title: "Pulp Fiction",
        year: 1994,
        type: "screenplay",
        description: "Interlocking crime stories in Los Angeles",
      },
      {
        slug: "inglourious-basterds",
        title: "Inglourious Basterds",
        year: 2009,
        type: "screenplay",
        description: "Alternate-history WWII revenge fantasy",
      },
    ],
  },
  {
    slug: "coen-brothers",
    name: "Joel & Ethan Coen",
    years: "b. 1954/1957",
    bio: "Filmmaking siblings whose dark humor, meticulous craft, and genre-hopping made them modern American masters.",
    influencedBy: ["mccarthy", "chayefsky"],
    influenced: [],
    works: [
      {
        slug: "fargo-screenplay",
        title: "Fargo",
        year: 1996,
        type: "screenplay",
        description: "Kidnapping gone wrong in snowy Minnesota",
      },
      {
        slug: "no-country-screenplay",
        title: "No Country for Old Men",
        year: 2007,
        type: "screenplay",
        description: "A hunter, a killer, and a satchel of cash",
      },
    ],
  },
  {
    slug: "cody",
    name: "Diablo Cody",
    years: "b. 1978",
    bio: "Oscar-winning screenwriter whose sharp, idiosyncratic voice brought teenage outsiders to the mainstream.",
    influencedBy: ["ephron"],
    influenced: [],
    works: [
      {
        slug: "juno",
        title: "Juno",
        year: 2007,
        type: "screenplay",
        description: "A teenager navigates an unplanned pregnancy",
      },
      {
        slug: "young-adult",
        title: "Young Adult",
        year: 2011,
        type: "screenplay",
        description: "A YA writer returns to her hometown",
      },
    ],
  },
  {
    slug: "peele",
    name: "Jordan Peele",
    years: "b. 1979",
    bio: "American filmmaker who turned social horror into a genre, weaponizing comedy and dread to expose American racism.",
    influencedBy: ["butler"],
    influenced: [],
    works: [
      {
        slug: "get-out",
        title: "Get Out",
        year: 2017,
        type: "screenplay",
        description: "A Black man visits his white girlfriend's family",
      },
      {
        slug: "us-screenplay",
        title: "Us",
        year: 2019,
        type: "screenplay",
        description: "A family confronts their doppelgangers",
      },
    ],
  },

  // ==================== TELEPLAY EMMY WINNERS ====================
  {
    slug: "chase",
    name: "David Chase",
    years: "b. 1945",
    bio: "Television auteur who created the golden age of prestige TV with the definitive American anti-hero.",
    influencedBy: ["chayefsky"],
    influenced: ["gilligan"],
    works: [
      {
        slug: "sopranos-pilot",
        title: "The Sopranos: Pilot",
        year: 1999,
        type: "screenplay",
        description: "A mob boss starts seeing a therapist",
      },
      {
        slug: "sopranos-finale",
        title: "The Sopranos: Made in America",
        year: 2007,
        type: "screenplay",
        description: "The most debated finale in TV history",
      },
    ],
  },
  {
    slug: "gilligan",
    name: "Vince Gilligan",
    years: "b. 1967",
    bio: "American television writer-producer who charted the complete moral disintegration of an ordinary man.",
    influencedBy: ["mccarthy", "chase"],
    influenced: [],
    works: [
      {
        slug: "breaking-bad-pilot",
        title: "Breaking Bad: Pilot",
        year: 2008,
        type: "screenplay",
        description: "A chemistry teacher turns to cooking meth",
      },
      {
        slug: "ozymandias",
        title: "Breaking Bad: Ozymandias",
        year: 2013,
        type: "screenplay",
        description: "The empire crumbles — highest-rated TV episode ever",
      },
    ],
  },
  {
    slug: "simon",
    name: "David Simon",
    years: "b. 1960",
    bio: "Former journalist who turned Baltimore's institutions into the most ambitious sociological drama ever televised.",
    influencedBy: ["didion", "baldwin"],
    influenced: [],
    works: [
      {
        slug: "wire-pilot",
        title: "The Wire: The Target",
        year: 2002,
        type: "screenplay",
        description: "The drug war from every angle",
      },
      {
        slug: "show-me-hero",
        title: "Show Me a Hero",
        year: 2015,
        type: "screenplay",
        description: "Public housing and political ambition in Yonkers",
      },
    ],
  },
  {
    slug: "coel",
    name: "Michaela Coel",
    years: "b. 1987",
    bio: "British writer-actor whose fearless, formally inventive work confronts consent, trauma, and identity with radical honesty.",
    influencedBy: ["waller-bridge", "baldwin"],
    influenced: [],
    works: [
      {
        slug: "i-may-destroy-you",
        title: "I May Destroy You",
        year: 2020,
        type: "screenplay",
        description: "Reconstructing identity after sexual assault",
      },
      {
        slug: "chewing-gum",
        title: "Chewing Gum",
        year: 2015,
        type: "screenplay",
        description: "A sheltered young woman discovers the world",
      },
    ],
  },
];

export function getCreatorBySlug(slug: string): Creator | undefined {
  return creators.find((c) => c.slug === slug);
}

export function getAllCreators(): Creator[] {
  return creators;
}

export function getLineage(slug: string): {
  ancestors: Creator[];
  descendants: Creator[];
} {
  const creator = getCreatorBySlug(slug);
  if (!creator) return { ancestors: [], descendants: [] };

  const ancestors = creator.influencedBy
    .map((s) => getCreatorBySlug(s))
    .filter((c): c is Creator => c !== undefined);

  const descendants = creator.influenced
    .map((s) => getCreatorBySlug(s))
    .filter((c): c is Creator => c !== undefined);

  return { ancestors, descendants };
}
